version: "2.4"

services:
  accountdb:
    image: postgres:14.0-alpine
    user: "postgres"
    healthcheck:
      test: [ CMD-SHELL, "pg_isready -d accounts" ]
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=accounts"
    volumes:
      - "dev-accountdb-data:/var/lib/postgresql/data"

  abusedb:
    image: postgres:14.0-alpine
    user: "postgres"
    healthcheck:
      test: [ CMD-SHELL, "pg_isready -d abuse" ]
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=abuse"
    volumes:
      - "dev-abusedb-data:/var/lib/postgresql/data"

  redis-cluster:
    image: grokzen/redis-cluster:6.2.0
    ports:
      - "7000-7002:7000-7002"
    healthcheck:
      test: [ CMD-SHELL, "redis-cli -p 7000 cluster info | grep ^cluster_state:ok" ]
    environment:
      - "SLAVES_PER_MASTER=0"
      - "IP=0.0.0.0"
    volumes:
      - "dev-redis-data:/redis-data"

  localstack:
    image: localstack/localstack:1.2.0
    healthcheck:
      test: [ CMD-SHELL, "awslocal dynamodb list-tables && awslocal s3 ls" ]
    ports:
      - "4566:4566"
    environment:
      - "DISABLE_EVENTS=1"
    volumes:
      - "dev-localstack-data:/var/lib/localstack"

  envoy:
    image: envoyproxy/envoy-alpine:v1.20.0
    healthcheck:
      test: [ CMD-SHELL, "wget -q --spider http://127.0.0.1:9901/ready || exit 1" ]
    network_mode: host
    volumes:
      - "./envoy/envoy.yml:/etc/envoy/envoy.yaml:ro"
      - "./envoy/localhost.pem:/etc/envoy/localhost.pem:ro"
      - "./envoy/localhost.key:/etc/envoy/localhost.key:ro"

  bigtable:
    image: fullstorydev/cbtemulator:v0.1.0
    ports:
      - "8086:9000"
    volumes:
      - "dev-bigtable-data:/data"

volumes:
  dev-accountdb-data:
  dev-abusedb-data:
  dev-redis-data:
  dev-localstack-data:
  dev-bigtable-data:
